/* GPIO impl.h for RZ/A1H */
#ifndef _IMPL_GPIO_H_
#define _IMPL_GPIO_H_

#include <stdint.h>

#ifdef __cplusplus 
extern "C" {
#endif

#define GPIO1_PHYSICAL_ADR (0xfcfe3000)
#define GPIO2_PHYSICAL_ADR (0xfcfe7000)

#define GPIO_BASE1 GPIO1_PHYSICAL_ADR

#define GPIO_P_OFFSET 0x0
#define GPIO_PSR_OFFSET 0x100
#define GPIO_PPR_OFFSET 0x200
#define GPIO_PM_OFFSET 0x300
#define GPIO_PMC_OFFSET 0x400
#define GPIO_PFC_OFFSET 0x500
#define GPIO_PFCE_OFFSET 0x600
#define GPIO_PNOT_OFFSET 0x700
#define GPIO_PMSR_OFFSET 0x800
#define GPIO_PMCSR_OFFSET 0x900
#define GPIO_PFCAE_OFFSET 0xa00

#define GPIO_BASE2 GPIO2_PHYSICAL_ADR

#define GPIO_PIBC_OFFSET 0x0
#define GPIO_PBDC_OFFSET 0x100
#define GPIO_PIPC_OFFSET 0x200

#define GPIO_PORTADDR(base, width, offset, port) \
	(*(uint##width##_t *)(base + offset + 4 * (port)))

#define GPIO_P(p) GPIO_PORTADDR(GPIO_BASE1, 16, GPIO_P_OFFSET, (p))
#define GPIO_PSR(p) GPIO_PORTADDR(GPIO_BASE1, 32, GPIO_PSR_OFFSET, (p))
#define GPIO_PPR(p) GPIO_PORTADDR(GPIO_BASE1, 16, GPIO_PPR_OFFSET, (p))
#define GPIO_PM(p) GPIO_PORTADDR(GPIO_BASE1, 16, GPIO_PM_OFFSET, (p))
#define GPIO_PMC(p) GPIO_PORTADDR(GPIO_BASE1, 16, GPIO_PMC_OFFSET, (p))
#define GPIO_PFC(p) GPIO_PORTADDR(GPIO_BASE1, 16, GPIO_PFC_OFFSET, (p))
#define GPIO_PFCE(p) GPIO_PORTADDR(GPIO_BASE1, 16, GPIO_PFCE_OFFSET, (p))
#define GPIO_PNOT(p) GPIO_PORTADDR(GPIO_BASE1, 16, GPIO_PNOT_OFFSET, (p))
#define GPIO_PMSR(p) GPIO_PORTADDR(GPIO_BASE1, 32, GPIO_PMSR_OFFSET, (p))
#define GPIO_PMCSR(p) GPIO_PORTADDR(GPIO_BASE1, 32, GPIO_PMCSR_OFFSET, (p))
#define GPIO_PFCAE(p) GPIO_PORTADDR(GPIO_BASE1, 16, GPIO_PFCAE_OFFSET, (p))

#define GPIO_PIBC(p) GPIO_PORTADDR(GPIO_BASE2, 16, GPIO_PIBC_OFFSET, (p))
#define GPIO_PBDC(p) GPIO_PORTADDR(GPIO_BASE2, 16, GPIO_PBDC_OFFSET, (p))
#define GPIO_PIPC(p) GPIO_PORTADDR(GPIO_BASE2, 16, GPIO_PIPC_OFFSET, (p))

#ifdef __cplusplus 
}
#endif
#endif 